### ISSUE TITLE
TypeError: Storage.download() missing 1 required positional argument: 'filename'

### ISSUE THREAD

**Issue by jeremyredhead** [space-elephant/tinyworld-textmode#4]
When I run play.py without --local flag I get this mysterious error:

<details><summary>Stack trace</summary>

```
Exception in thread Thread-1 (download):
Traceback (most recent call last):
Exception in thread Thread-2 (download):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Play? (Y/n) Traceback (most recent call last):
Exception in thread Thread-3 (download):
Traceback (most recent call last):
    self.run()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
    self.run()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
  File "C:\Users\<user>\Documents\GitRepos\tinyworld-textmode\play.py", line 76, in download
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    storage.child(file[6:]).download(file)
TypeError: Storage.download() missing 1 required positional argument: 'filename'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "C:\Users\<user>\Documents\GitRepos\tinyworld-textmode\play.py", line 76, in download
  File "C:\Users\<user>\Documents\GitRepos\tinyworld-textmode\play.py", line 76, in download
    storage.child(file[6:]).download(file)
    storage.child(file[6:]).download(file)
TypeError: Storage.download() missing 1 required positional argument: 'filename'
TypeError: Storage.download() missing 1 required positional argument: 'filename'
```
</details>

I mean, it sure looks like you properly passed in the filename argument to me, so IDK what's going on here.

**Comment by space-elephant** [comment]
Can you prevent all the threads from writing to stderr at the same time? I can't actually read any of the traces when they are all jumbled together. Try commenting out lines 89 and 90 of play.py. (Although, all three should actually be conditional on deprotect, since the tutorials were protected in the original.)
Like your other problem, it works on my machine, so I can't really debug it myself. This one is a lot stranger though: I can't see how it could be microsoft's fault.

**Comment by jeremyredhead** [comment]
> lines 89 and 90 [...] should actually be conditional on `deprotect`

Oops, sorry about that, was on an older commit & forgot to git fetch & pull 

Anyways, the underlying issue is still eludes me as well; 
If I run play.py, hit Enter, then quit, I am greeted by this traceback from the `startdownload` on line 427:

```
Exception in thread Thread-1 (download):
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\<user>\Documents\GitRepos\tinyworld-textmode\play.py", line 76, in download
    storage.child(file[6:]).download(file)
TypeError: Storage.download() missing 1 required positional argument: 'filename'
```

> I can't see how it could be microsoft's fault.

Me neither.

I have a burning suspicion that `pyrebase4` and/or the "windows-compatible" vesion of `pycryptodome` it depends upon, are buggy on Windows. But I haven't tried digging into either of their codebases to verify this, and I afraid to say I am quite out of my element when it comes to threading, networking, or whatever it is that pycryptodome does.

**Comment by space-elephant** [comment]
Ok, does it work if you change that line to `storage.child(file[6:]).download(filename=file)`?
If not, can you show me the file that that function is defined in? It should be part of the pyrebase package, which *should* be the same in pyrebase4, but it might be out of date or something. For me, `~/.local/lib/python3.9/site-packages/pyrebase/pyrebase.py` contains, on line 412, `def download(self, filename, token=None):`
Also, the threading isn't part of pyrebase or any other dependencies. I use a separate thread for each download because the actual `Storage.download` function is blocking, and I couldn't find any alternatives.

**Comment by jeremyredhead** [comment]
> does it work if you change that line to 
> |storage.child(file[6:]).download(filename=file)|?

No, and it wouldn't even if I did; this is the definition of 
Storage.download in Pyrebase4 
<https://github.com/nhorvath/Pyrebase4/blob/master/pyrebase/pyrebase.py#L485>:

|def download(self, path, filename, token=None):|

This commit made the breaking change to |download| 
<https://github.com/nhorvath/Pyrebase4/commit/ea83957c5409a9e468bb5a21875f6f4c91b9aa23>, 
and it wasn't done properly,
so that path parameter isn't actually used in the case of 
unauthenticated downloads like in play.py

Since it is broken, I am planning on submitting a PR to Pyrebase4 to fix 
the path argument,
and possibly restore backwards compatibility of |download| with 
pyrebase, if possible.
It may be a while before it's merged, as Pyrebase4 seems to be only 
minimally maintained 
<https://github.com/nhorvath/Pyrebase4/blob/master/CODESHELTER.md>.

Might I ask why you initially chose pyrebase?
Aside from |download|, Pyrebase4 seems to be compatible with it, but 
unlike pyrebase, it is somewhat maintained.
It would certainly be simpler to switch to it (or a fork of it) then to 
try to write a wrapper function to paper over the change in |download|.

As it is now, to switch over to Pyrebase4, all the |download| calls need 
to look like this:

|.download(filename=file, path='') # path must be a string|

**Comment by jeremyredhead** [comment]
Oops, thought that GitHub would be smart enough to convert my HTML to Markdown... clearly not. Lesson learned I guess.
